export default {
  TEST_ACTION_PENDING :"TEST_ACTION_PENDING",
  TEST_ACTION_SUCCESS :"TEST_ACTION_SUCCESS",
  TEST_ACTION_FAIL :"TEST_ACTION_FAIL",

  CHANGE_CONNECTION_STATUS: 'CHANGE_CONNECTION_STATUS',
  CHANGE_LANGUAGE : 'CHANGE_LANGUAGE',

  CHANGE_THEME :"CHANGE_THEME",
}
