export default {
  TEST_ACTION_PENDING :"TEST_ACTION_PENDING",
  TEST_ACTION_SUCCESS :"TEST_ACTION_SUCCESS",
  TEST_ACTION_FAIL :"TEST_ACTION_FAIL",

  LOGIN_PENDING :"LOGIN_PENDING",
  LOGIN_SUCCESS :"LOGIN_SUCCESS",
  LOGIN_FAIL :"LOGIN_FAIL",

  CHANGE_CONNECTION_STATUS: 'CHANGE_CONNECTION_STATUS',
  CHANGE_LANGUAGE : 'CHANGE_LANGUAGE'
}
